export class ServicesLst {
  static readonly apiAddress = {
    PersistChangePOFromIconX: '/APIService.asmx/PersistChangePOFromIconX?',
    GetDeviceInfoByIMEI: '/SamsungKnox/GetDeviceInfoByIMEI?',
    GetModuleWikiURL: '/ApplicationModule/GetModuleWikiURL?',
    GetPunchAvailability: '/RAP/GetPunchAvailability?',
    GetEmployeePunchStatus: '/RAP/GetEmployeePunchStatus?',
    EmployeePunchIn: '/RAP/EmployeePunchIn',
    EmployeePunchOut: '/RAP/EmployeePunchOut',
    UnLock: '/Account/Unloack',
    DeleteAccount: '/Account/DropUser',
    Authenticate: '/Authentication/Authenticate',
    CreateAccount: '/Account/Register',
    ResetPassword: '/Account/ResetPasswordbyuserName',
    EventLog: '/EventLog/Get?OfpInstanceID=',
    GetBussinessSummary: '/APISummary.asmx/GetBussinessSummary',
    SentMessage: '/SentMessage/Get?',
    GetCredit: '/SentMessage/GetCredit',
    OrderDownload: '/OrderDownload/Get?fromDate=',
    BlockOrder: '/SentMessage/BlockOrder?orderNo=',
    UnBlockOrder: '/SentMessage/UnBlockOrder?orderNo=',
    GetsummaryJson: '/APISummary.asmx/GetsummaryJson',
    GetTracerCount: '/tracer/GetTracerCount',
    GetOnProcessItems: '/tracer/GetOnProcessItems',
    GetExceptionItems: '/tracer/GetExceptionItems',
    GetQueueItems: '/tracer/GetQueueItems',
    manualDownload: '/OrderDownload/manualDownload',
    GetBPMN2SourceDigaram: '/Workflow/GetBPMN2SourceDigaram?OfpHeaderId=',
    Disable: '/Account/Disable',
    Enable: '/Account/Enable',
    frmNewPoDetail: '/frmNewPoDetail.aspx?PoNo=',
    LWView: '/frmShowOrderAttachment.aspx?OrderNo=',
    MeasureView: '/frmShowOrderAttachment.aspx?OrderNo=',
    EPAView: '/frmShowOrderAttachment.aspx?OrderNo=',
    WorkOrder: '/frmShowOrderAttachment.aspx?OrderNo=',
    poStatus: '/po/GetPOSerach?poStatus=',
    FollowUpActions: '/po/GetPOSerach?FollowUpActions=',
    JobTypes: '/po/GetPOSerach?JobTypes=',
    IconXSync: '/po/IconXSync?',
    SetPODiscripencyDate: '/PO/SetPODiscripencyDate?',
    GetPODiscripencyDate: '/PO/GetPODiscripencyDate',
    workflow: '/workflow/get?',
    StartNewWorkflow: '/workflow/StartNewWorkflow',
    GetAllByOFPHeaderId: '/workflow/GetAllByOFPHeaderId?OFPheaderId=',
    GetAllRoles: '/account/GetAllRoles',
    CreateRole: '/account/CreateRole?rolename=',
    DeleteRole: '/account/DeleteRole?rolename=',
    GetRolesForUser: '/account/GetRolesForUser?userName=',
    AddUsersToRoles: '/account/AddUsersToRoles',
    RemoveUsersFromRoles: 'BPMSAPIService/api/account/RemoveUsersFromRoles',
    GetUsersInRole: '/account/GetUsersInRole?rolename=',
    GetSegmentationTypes: '/account/GetSegmentationTypes',
    GetSegmentationCodeByTypeId:
      '/account/GetSegmentationCodeByTypeId?SegmentationTypeId=',
    SignUp: '/Account/SignUp',
    GetSegmentationByRole: '/Account/GetSegmentationByRole?',
    GetAssignApplicationModule: '/Account/GetAssignApplicationModule?',
    AddUsersToRolesBySegment: '/Account/AddUsersToRolesBySegment',
    EditUsersToRolesBySegment: '/Account/EditUsersToRolesBySegment',
    GetRoleSegmentbyUserId: '/Account/GetRoleSegmentbyUserId?',
    RemoveUsersToRolesBySegment: '/Account/RemoveUsersToRolesBySegment',
    SetDefualtRoleForUser: '/Account/SetDefualtRoleForUser',
    UpdateRole: '/Account/UpdateRole?',
    FormAdd: '/Form/Add',
    GetFormById: '/Form/GetByFormId?',
    GetSurveyComponent: '/CheckList/GetSurveyComponent?',
    GetcheckListType: '/CheckList/GetcheckListType?',
    UpdateSurveyComponent: '/CheckList/UpdateSurveyDetail',
    GetAllForm: '/Form/GetAll',
    UserList: '/account/Get?',
    AccountDetail: '/account/Get?userID=',
    TaskList: '/Task/Get',
    login: '/account/login',
    GetRequestId: '/account/GetRequestId?userId=',
    GetParent: '/ApplicationModule/GetParent?RoleName=',
    GetChild: '/ApplicationModule/GetChild?ParentId=',
    AddApplicationModule: '/ApplicationModule/add',
    GetTaskByRoles: '/Task/GetByRoles',
    GetWaitingTaskByRoles: '/Task/GetWaitingByRoles',
    GetAllTaskByRoles: '/Task/GetAllTaskByRoles',
    AccountRegister: '/Account/Register',
    GetAllActivityByIMEI: '/account/GetAllActivityByIMEI?',
    GetCurrentDeviceLocationHistoryByIMEI:
      '/SamsungKnox/GetCurrentDeviceLocationHistoryByIMEI?',
    GetLCurrentLocationInfo: '/Location/GeGetDistanceInfo?',
    AssigntoRole: '/ApplicationModule/AssigntoRole',
    GetByRoleName: '/ApplicationModule/GetByRoleName?RoleName=',
    DeleteApplicationModule: '/ApplicationModule/Delete?ApplicationModule=',
    UpdateApplicationModule: '/ApplicationModule/Update',
    GetTypeApplicationModule: '/ApplicationModule/GetType',
    GetHomePages: '/ApplicationModule/GetHomePages',
    GetHomPageByRoleName: '/ApplicationModule/GetHomPageByRoleName?',
    GetByTaskRef: '/Component/GetByTaskRef?TaskRef=',
    SaveComponent: '/Component/Save',
    SubmitComponent: '/Task/submit',
    GetOrderSurface: '/Order/GetOrderSurface',
    GetOrderKind: '/Order/GetOrderKind',
    GetProcess: '/Workflow/GetForSearch',
    GetOrders: '/Order/GetOrders',
    GetProjects: '/Project/GetProjects',
    GetOrderJobs: '/OrderProcessing/GetOrderJobs?OrderNo=',
    GetRequirements: '/OrderProcessing/GetRequirements?OrderNo=',
    ChangePassword: '/Account/ChangePassword',
    GetAllInstallerUser: '/Account/GetAllInstallerUser',
    GetOFPResourceById: '/workflow/GetOFPResourceById?OFPResourceId=',
    GetEventAction: '/Event/GetEventActionByEventId?EventId=',
    GetEventParameter: '/Event/Get?EventId=',
    GetSubWorkTeamCalendar: '/Team/GetSubWorkTeamCalendar?',
    GetSubWorkTeamSkill: '/Team/GetSubWorkTeamSkill?',
    UpdateWorkTeamSkill: '/Team/UpdateWorkTeamSkill',
    GetTeamSkillLevel: '/Team/GetTeamSkillLevel',
    GetTeamSkillMain: '/Team/GetTeamSkillMain',
    GetSuspendByRoles: '/Task/FindSuspendTask',
    Recover: '/Task/Recover',
    ResetAll: '/Task/ResetAll',
    FindSuspendTaskOnTracer: '/Task/FindSuspendTaskOnTracer',
    GetEmail: '/Notification/GetEmail?',
    GetPhone: '/Notification/GetPhone?',
    GetTeamAvailability: '/Team/GetTeamAvailability',
    UpdateWorkTeamCalendar: '/Team/UpdateWorkTeamCalendar?',
    CreateTeamBPMSAccount: '/Team/CreateTeamBPMSAccount?',
    GetTaskCount: '/Task/GetTaskCount',
    GetOrdersCount: '/Order/GetOrdersCount',
    GetAllParameter: '/Parameter/GetAll',
    GetByIdParameter: '/Parameter/GetById?',
    GetAllType: '/Parameter/GetAllType',
    GetByOFPHeaderId: '/Component/GetByOFPHeaderId?',
    GetAllEvent: '/Event/GetAll',
    GetAllEvents: '/Event/GetAllEvents',
    AssignRoleToEvent: '/Event/AssignRole',
    GetRoleId: '/Account/GetRoleId?RoleName=',
    GetAllForRole: '/Event/GetAllForRole?roleId=',
    GetAllEventForUser: '/Account/GetAllEventForuser?userName=',
    GetRoleByApplicationModuleId: '/account/GetRoleByApplicationModuleId?',
    GetAllEventForRole: '/Account/GetAllEventForRole?',
    GetJsonByTaskRef: '/Component/GetJsonByTaskRef?TaskRef=',
    GetAllOrderAttachments: '/OrderAttachment/GetAllOrderAttachments?OrderNo=',
    GetAllAttachmentTypes: '/OrderAttachment/GetAllAttachmentTypes',
    GetComplianceAttachmentTypes:
      '/OrderAttachment/GetComplianceAttachmentTypes?',
    GetOrderAttachment: '/OrderAttachment/Get?',
    UploadFiles: '/OrderAttachment/UploadFiles?orderNo=',
    UploadFilesByUserName: '/OrderAttachment/UploadFilesByUserName?orderNo=',
    AddOrderAttachment: '/OrderAttachment/Add',
    GetInstallerGrid: '/Scheduling/GetInstallerGrid?',
    GetPhoneNumbers: '/CallCenter/GetPhoneNumbers?',
    GetPODiscripency: '/PO/GetPODiscripency?',
    GetNotify: '/OrderDownload/GetNotify?',
    GetExtension: '/CallCenter/GetExtension?Account_Id=',
    GetPhoneKinds: '/CallCenter/GetPhoneKinds?PhoneType=',
    GetPhoneTypes: '/CallCenter/GetPhoneTypes',
    UpdatePhone: '/CallCenter/UpdatePhone',
    InsertPhone: '/CallCenter/InsertPhone',
    DeletePhone: '/CallCenter/DeletePhone',
    GetCallHistoryByPhoneNo: '/CallCenter/GetCallHistoryByPhoneNo',
    GetCFBtelAgents: '/CallCenter/GetCFBtelAgents',
    GetPhones: '/CallCenter/GetPhones?',
    GetPhonesKinds: '/CallCenter/GetPhonesKinds',
    GetPhonesTypes: '/CallCenter/GetPhonesTypes',
    InsertPhones: '/CallCenter/InsertPhones',
    UpdatePhones: '/CallCenter/UpdatePhones',
    DeletePhones: '/CallCenter/DeletePhones',
    GetLatestPhones: '/CallCenter/GetLatestPhones?',
    GetLocalMisscallsCount: '/CallCenter/GetLocalMisscallsCount?',
    GetByOrderNo: '/EventLog/GetByOrderNo?OrderNo=',
    ManualMeasureDownload: '/OrderDownload/ManualMeasureDownload?',
    GetManualEPA: '/OrderDownload/GetManualEPA?',
    ManualDownloadNotExist: '/OrderDownload/ManualDownloadNotExist',
    PODownloadException: '/OrderDownload/PODownloadException',
    PODownloadRecover: '/OrderDownload/PODownloadRecover?',
    GetOFPInstanceByOrderNo: '/EventLog/GetOFPInstanceByOrderNo?OrderNo=',
    GetOrderHistory: '/OrderProcessing/GetOrderHistory?OrderNo=',
    GetScheduleHistory: '/OrderProcessing/GetScheduleHistory?OrderNo=',
    GetMileage: '/OrderProcessing/GetMileage?ProjectNo=',
    OrderStop: '/OrderProcessing/OrderStop',
    GetCancelReasons: '/OrderProcessing/GetCancelReasons?',
    GetJobDownReasons: '/OrderProcessing/GetJobDownReasons',
    GetOrderAR: '/OrderProcessing/GetOrderAR?OrderNo=',
    GetOrderAP: '/OrderProcessing/GetOrderAP?OrderNo=',
    GetOrderChange: '/OrderProcessing/GetOrderChange?OrderNo=',
    GetOrderChangeJobs: '/OrderProcessing/GetOrderChangeJobs?OrderChangeId=',
    GetOrderChangeMaterials:
      '/OrderProcessing/GetOrderChangeMaterials?OrderChangeId=',
    GetOrderChangeStatus: '/OrderProcessing/GetOrderChangeStatus',
    GetOrderChangeSource: '/OrderProcessing/GetOrderChangeSource',
    GetOrderChangeType: '/OrderProcessing/GetOrderChangeType',
    OrderChangeInsert: '/OrderProcessing/OrderChangeInsert',
    GetOrdChangeJobOperationList:
      '/OrderProcessing/GetOrdChangeJobOperationList?OrderNo=',
    GetOrderExpense: '/OrderProcessing/GetOrderExpense?OrderNo=',
    GetSurveyHeader: '/CheckList/GetSurveyHeader?OrderNo=',
    GetSurveyDetail: '/CheckList/GetSurveyDetail?SurveyNo=',
    OrderChangeJobInsert: '/OrderProcessing/OrderChangeJobInsert',
    GetOrderChangeMatItemsList:
      '/OrderProcessing/GetOrderChangeMatItemsList?OrderNo=',
    OrderChangeMaterialInsert: '/OrderProcessing/OrderChangeMaterialInsert',
    OrderChangeUpdate: '/OrderProcessing/OrderChangeUpdate?',
    OrderChangeJobUpdate: '/OrderProcessing/OrderChangeJobUpdate?',
    OrderGetTeamArrangement: '/OrderProcessing/GetTeamArrangement?OrderNo=',
    GetTeamArrangementMembers:
      '/OrderProcessing/GetTeamArrangementMembers?OfficeCode=',
    AddTeamArrangementMembers: '/OrderProcessing/TeamArrangementAdd?orderNo=',
    ResetTeamArrangement: '/OrderProcessing/TeamArrangementReset?orderNo=',
    ConfirmTeamArrangement: '/OrderProcessing/TeamArrangementConfirm?orderNo=',
    RemoveTeamArrangementMembers:
      '/OrderProcessing/TeamArrangementRemove?orderNo=',
    OrderChangeMaterialUpdate: '/OrderProcessing/OrderChangeMaterialUpdate?',
    OrderChangeDelete: '/OrderProcessing/OrderChangeDelete?OrderChangeId=',
    OrderChangeJobDelete:
      '/OrderProcessing/OrderChangeJobDelete?OrderChangeJobId=',
    OrderChangeMaterialDelete:
      '/OrderProcessing/OrderChangeMaterialDelete?OrderChangeMaterialId=',
    ConfirmOrderExpnese: '/OrderProcessing/ConfirmExpense?orderNo=',
    ExpenseUpdate: '/OrderProcessing/ExpenseUpdate?id=',
    OrderChangeCancel: '/OrderProcessing/OrderChangeCancel?OrderChangeId=',
    OrderChangeDone: '/OrderProcessing/OrderChangeDone?OrderChangeId=',
    OrderChangeOpen: '/OrderProcessing/OrderChangeOpen?OrderChangeId=',
    GetChecklistType: '/CheckList/GetSurveyHeaderCheckLists?MasterFieldCode=',
    GetChecklistWorker: '/CheckList/GetSurveyHeaderWorkers',
    GetChecklistInitiator: '/CheckList/GetSurveyHeaderInitiators',
    ChecklistHeaderUpdate: '/CheckList/UpdateSurveyHeader?SurveyNo=',
    ChecklistHeaderInsert: '/CheckList/InsertSurveyHeader',
    ChecklistHeaderConfirm: '/CheckList/ConfirmSurvey',
    ChecklistHeaderReset: '/CheckList/ResetSurvey?SurveyNo=',
    RequirementUpdate: '/OrderProcessing/RequirementUpdate',
    JobUpdate: '/OrderProcessing/JobUpdate',
    ConfirmMaterial: '/OrderProcessing/ConfirmMaterial?orderNo=',
    QuickBOR: '/OrderProcessing/QuickBOR?orderNo=',
    MoveRequirement: '/OrderProcessing/MoveRequirement?orderNo=',
    RequirementInsert: '/OrderProcessing/RequirementInsert',
    RequirementDelete: '/OrderProcessing/RequirementDelete?orderNo=',
    JobInsert: '/OrderProcessing/JobInsert',
    JobDelete: '/OrderProcessing/JobDelete?orderNo=',
    GetOrderStatus: '/OrderProcessing/GetOrderStatus',
    GetOrderComplain: '/OrderProcessing/GetOrderComplain?MasterOrderNo=',
    GetOrderComplainHeader:
      '/OrderProcessing/GetOrderComplainHeader?MasterOrderNo=',
    GetComplainOrders: '/OrderProcessing/GetComplainOrders?ComplainNo=',
    GetComplainAccounting: '/OrderProcessing/GetComplainAccounting?ComplainNo=',
    DeleteComplainOrder: '/OrderProcessing/DeleteComplainOrder?OrderNo=',
    ComplainConfirm: '/OrderProcessing/ComplainConfirm?ComplainNo=',
    GetComplainChargebacks:
      '/OrderProcessing/GetComplainChargebacks?ComplainNo=',
    UpdateComplain: '/OrderProcessing/UpdateComplain',
    InsertComplain: '/OrderProcessing/InsertComplain',
    UpdateComplainOrder: '/OrderProcessing/UpdateComplainOrder',
    InsertComplainOrder: '/OrderProcessing/InsertComplainOrder',
    GetComplainAgainst: '/OrderProcessing/GetComplainAgainst',
    GetComplainLookupList: '/OrderProcessing/GetComplainLookupList?',
    GetComplainOrdersMethods: '/OrderProcessing/GetComplainOrdersMethods',
    GetComplainOrdersList: '/OrderProcessing/GetComplainOrdersList?ProjectNo=',
    DeleteChargeback: '/OrderProcessing/DeleteChargeback?',
    GetComplainSeverity: '/OrderProcessing/GetComplainSeverity',
    GetComplainGeneralCategory: '/OrderProcessing/GetComplainGeneralCategory?',
    GetComplainOrdersIncharge: '/OrderProcessing/GetComplainOrdersIncharge',
    GetComplainSource: '/OrderProcessing/GetComplainSource',
    GetComplainSpecificCategory:
      '/OrderProcessing/GetComplainSpecificCategory?',
    GetComplainSurveyList: '/OrderProcessing/GetComplainSurveyList?',
    GetBeforeInsertComplain: '/OrderProcessing/GetBeforeInsertComplain',
    ComplainAddInspection: '/OrderProcessing/ComplainAddInspection?',
    GetSubAssignment: '/OrderProcessing/GetSubAssignment?OrderNo=',
    UpdateSubAssignment: '/OrderProcessing/UpdateSubAssignment?',
    ComplainClose: '/OrderProcessing/ComplainClose?',
    ComplainOpen: '/OrderProcessing/ComplainOpen?',
    InsertChargeback: '/OrderProcessing/InsertChargeback',
    UpdateChargeback: '/OrderProcessing/UpdateChargeback',
    GetCustomerLoockupList: '/OrderProcessing/GetCustomerLoockupList?',
    GetChargebacksKinds: '/OrderProcessing/GetChargebacksKinds',
    GetChargebacksResults: '/OrderProcessing/GetChargebacksResults',
    GetChargebacksJobsList:
      '/OrderProcessing/GetChargebacksJobsList?MasterOrderNo=',
    GetOperations: '/OrderProcessing/GetOperations?ListOrderNo=',
    OrderSubmit: '/OrderProcessing/OrderSubmit?orderNo=',
    OrderDispatch: '/OrderProcessing/OrderDispatch?orderNo=',
    OrderComplete: '/OrderProcessing/OrderComplete?orderNo=',
    OrderLW: '/OrderProcessing/OrderLW?orderNo=',
    OrderApplyMin: '/OrderProcessing/OrderApplyMin?orderNo=',
    OrderUnapplyMin: '/OrderProcessing/OrderUnapplyMin?orderNo=',
    OrderHold: '/OrderProcessing/OrderHold?orderNo=',
    OrderUnHold: '/OrderProcessing/OrderUnHold?orderNo=',
    OrderPriceCalculate: '/OrderProcessing/OrderPriceCalculate?orderNo=',
    OrderDelete: '/OrderProcessing/OrderDelete?orderNo=',
    OrderInsert: '/OrderProcessing/OrderInsert',
    OrderUpdate: '/OrderProcessing/OrderUpdate',
    GetSurveyHeaderInfo: '/CheckList/GetSurveyHeaderInfo?SurveyNo=',
    GetMethods: '/OrderProcessing/GetMethods',
    GetKinds: '/OrderProcessing/GetKinds',
    GetItems: '/OrderProcessing/GetItems?',
    GetDeliveries: '/OrderProcessing/GetDeliveries',
    signalR: '/signalr/hubs',
    DeleteAttachment: '/OrderAttachment/Delete?',
    ConvertToCC: '/OrderProcessing/ConvertToCC?',
    OrderChangeApply: '/OrderProcessing/OrderChangeApply?',
    OrderChangeNotifyStore: '/OrderProcessing/OrderChangeNotifyStore?',
    GetProjectMasterOrders: '/OrderProcessing/GetProjectMasterOrders?',
    ProjectInsert: '/OrderProcessing/ProjectInsert',
    ProjectUpdate: '/OrderProcessing/ProjectUpdate',
    ProjectDelete: '/OrderProcessing/ProjectDelete?',
    GetStores: '/OrderProcessing/GetStores?',
    GetOrderSplit: '/OrderProcessing/GetOrderSplit?',
    OrderSplitUpdate: '/OrderProcessing/OrderSplitUpdate?',
    SplitOrder: '/OrderProcessing/SplitOrder?',
    RequirementSplit: '/OrderProcessing/RequirementSplit?',
    OrderEvenSplit: '/OrderProcessing/OrderEvenSplit?',
    GetOrderSplitHistory: '/OrderProcessing/GetOrderSplitHistory?',
    MergeSplittedOrders: '/OrderProcessing/MergeSplittedOrders?',
    GetProjectOrders: '/OrderProcessing/GetProjectOrders?',
    GetOrderChangeMatDeliveries: '/OrderProcessing/GetOrderChangeMatDeliveries',
    GetProjectMergeCandidates: '/OrderProcessing/GetProjectMergeCandidates?',
    ProjectMerge: '/OrderProcessing/ProjectMerge?',
    GetComplainStatuses: '/OrderProcessing/GetComplainStatuses',
    GetTags: '/OrderProcessing/GetTags',
    GetTagValues: '/OrderProcessing/GetTagValues?',
    GetRequirements4Filter: '/OrderProcessing/GetRequirements4Filter?',
    GetBOR: '/OrderProcessing/GetBOR?',
    InsertUserNavigationLog: '/OrderProcessing/InsertUserNavigationLog?',
    GetRequirementsEntranceExit:
      '/OrderProcessing/GetRequirementsEntranceExit?',
    GetComplainMatChargebacks: '/OrderProcessing/GetComplainMatChargebacks?',
    InsertMatChargeback: '/OrderProcessing/InsertMatChargeback',
    UpdateMatChargeback: '/OrderProcessing/UpdateMatChargeback?',
    DeleteMatChargeback: '/OrderProcessing/DeleteMatChargeback?',
    GetJobsDownTypes: '/OrderProcessing/GetJobsDownTypes',
    GetJobsDown: '/OrderProcessing/GetJobsDown?',
    ConfirmCheckedMaterial: '/OrderProcessing/ConfirmCheckedMaterial?',
    GetOrderNoteForOrderHistory:
      '/OrderProcessing/GetOrderNoteForOrderHistory?',
    DeleteComplain: '/OrderProcessing/DeleteComplain?',
    RecalculateProjectMileages: '/OrderProcessing/RecalculateProjectMileages?',
    GetAllServices: '/Service/GetAll',
    GetParameterByServiceId: '/Service/GetParameterByServiceId?',
    ServiceSave: '/Service/Save',
    GetAllServiceMask: '/ServiceMask/GetAll',
    AddServiceMask1: '/ServiceMask/ServiceMaskName?',
    GetServiceMaskParameter: '/ServiceMask/GetServiceMaskParameter?',
    GetServiceMaskService: '/ServiceMask/GetServiceMaskService?',
    ResetOrder: '/Order/ResetOrder?',
    ResetOrderViaOFPInstanceID: '/Order/ResetOrderViaOFPInstanceID?',
    AddServiceToServiceMask: '/ServiceMask/AddService?',
    SignAttachment: '/OrderAttachment/SignAttachment',
    GetOrderAddress: '/Scheduling/GetOrderAddress?',
    GetByEventId: '/Form/GetByEventId?',
    GetInstallerReuirements: '/Scheduling/GetInstallerReuirements?',
    GetReportsTree: '/ReportsPortal/GetReportsTree',
    SaveEventAction: '/Event/SaveEventAction?',
    GetSchedulingGrid: '/Scheduling/GetSchedulingGrid?',
    GetLastLocation: '/Location/GetLastLocation?',
    GetLastLocations: '/Location/GetLastLocations?',
    GetCurrentLocation: '/Location/GetCurrentLocation?',
    GetCapacityCounts: '/Scheduling/GetCapacityCounts?',
    CancelSchedule: '/Scheduling/CancelSchedule',
    Unassign: '/Scheduling/Unassign?',
    InstallerConfirm: '/Scheduling/InstallerConfirm?',
    InstallerAccept: '/Scheduling/InstallerAccept?',
    ConfirmSchedule: '/Scheduling/ConfirmSchedule',
    GetAMPM: '/Scheduling/GetAMPM',
    GetPriority: '/Scheduling/GetPriority',
    SyncOrder: '/Scheduling/SyncOrder',
    GetInstallers: '/Scheduling/GetInstallers?',
    GetschedulingCalendar: '/Scheduling/GetschedulingCalendar?',
    UpdateSchedule: '/Scheduling/UpdateSchedule',
    GetMonitoringGrid: '/Scheduling/GetMonitoringGrid?',
    GetPublicDef: '/GridColumnDef/GetPublicDef?',
    DeleteGridColumnDef: '/GridColumnDef/Delete?',
    GetSurfacesTree: '/Scheduling/GetSurfacesTree',
    GetSubs: '/Scheduling/GetSubs?',
    GetSchedulingInstallersGrid: '/Scheduling/GetSchedulingInstallersGrid?',
    GetDailyInstallerRoutes: '/Scheduling/GetDailyInstallerRoutes?',
    SyncScheduling: '/Scheduling/Sync',
    AddScheduleNote: '/Scheduling/AddScheduleNote',
    GetStoresUpdateReport: '/HomePage/GetStoresUpdateReport?',
    GetStoresUpdateCharts: '/HomePage/GetStoresUpdateCharts?',
    GetNewHomePageButtons: '/HomePage/GetNewHomePageButtons?',
    GetNewHomePageButtonSummary: '/HomePage/GetNewHomePageButtonSummary?',
    GetNewHomePageInfoSummary: '/HomePage/GetNewHomePageInfoSummary?',
    GetAllInvoices: '/Team/GetAllInvoices?',
    GetExpenseStatuses: '/Team/GetExpenseStatuses',
    DeleteInvoice: '/Team/DeleteInvoice?',
    ConfirmInvoice: '/Team/ConfirmInvoice?',
    InsertInvoice: '/Team/InsertInvoice?',
    GetTeamListForInvoice: '/Team/GetTeamListForInvoice?',
    GetStoreUpdateOtherInfo: '/HomePage/GetStoreUpdateOtherInfo?',
    InsertInvoiceExpense: '/Team/InsertInvoiceExpense',
    GetInvoiceExpenses: '/Team/GetInvoiceExpenses?',
    GetExpensePayKinds: '/Team/GetExpensePayKinds',
    GetExpenseItems: '/Team/GetExpenseItems',
    DeleteInvoiceExpense: '/Team/DeleteInvoiceExpense?',
    UpdateInvoiceExpense: '/Team/UpdateInvoiceExpense',
    GetStoreHomePageData: '/HomePage/GetStoreHomePageData?',
    GetStoreHomePageChart: '/HomePage/GetStoreHomePageChart?',
    GetStoreHomePageGrid: '/HomePage/GetStoreHomePageGrid?',
    GetOrderProcessingNavigation:
      '/OrderProcessing/GetOrderProcessingNavigation?',
    GetAllServiceCall: '/Workflow/GetAllServiceCall',
    GetTeams: '/Team/GetTeams?',
    GetTeamType: '/Team/GetTeamType',
    GetTeamShareType: '/Team/GetTeamShareType',
    GetTeamMemberType: '/Team/GetTeamMemberType',
    GetSubledger: '/Team/GetSubledger?',
    TeamInsert: '/Team/TeamInsert',
    TeamUpdate: '/Team/TeamUpdate',
    TeamDelete: '/Team/TeamDelete?',
    GetCallRecord: '/CallCenter/GetCallRecord?uniqId=',
    CFBTELLogin: '/v1/auth/login',
    CFBTELAllCalls: '/v1/cdr/all',
    GetCallRecordListByProjectNo: '/CallCenter/GetCallRecordListByProjectNo?',
    GetContractHeaders: '/Team/GetContractHeaders?',
    GetStoreOfficeInfo: '/HomePage/GetStoreOfficeInfo?',
    GetContentforStore: '/ContentManagement/GetContentforStore?',
    SaveContentforStore: '/ContentManagement/Save',
    GetAllContent: '/ContentManagement/GetAllContent?',
    GetMain: '/Team/GetMain',
    GetContractServiceline: '/Team/GetContractServiceline',
    GetDomain: '/Team/GetDomain?',
    GetExternalServiceResults: '/workflow/GetExternalServiceResults',
    GetExternalServices: '/workflow/GetExternalServices',
    GetServiceCallDetail: '/workflow/GetServiceCallDetail?',
    GetServiceCallHistory: '/workflow/GetServiceCallHistory?',
    InsertContractHeader: '/Team/InsertContractHeader',
    UpdateContractHeader: '/Team/UpdateContractHeader',
    ContractHeaderDelete: '/Team/ContractHeaderDelete?',
    ApproveContract: '/Team/ApproveContract?',
    GetDefaultApproveDate: '/Team/GetDefaultApproveDate?',
    ExpireContract: '/Team/ExpireContract?',
    CopySingleToCurrentContract: '/Team/CopySingleToCurrentContract',
    CopySpecificContractsToCurrentTeam:
      '/Team/CopySpecificContractsToCurrentTeam',
    CopyBasicPriceListToCurrentTeam: '/Team/CopyBasicPriceListToCurrentTeam?',
    GetContractDetail: '/Team/GetContractDetail?',
    GetExternalServicesmethod: '/workflow/GetExternalServicesmethod?',
    GetContractDetailKind: '/Team/GetContractDetailKind',
    GetServicelineOperations: '/Team/GetServicelineOperations?',
    InsertContractDetail: '/Team/InsertContractDetail',
    UpdateContractDetail: '/Team/UpdateContractDetail',
    ContractDetailDelete: '/Team/ContractDetailDelete?',
    CreateContractLog: '/Team/CreateContractLog?',
    CopyContractFromDate: '/Team/CopyContractFromDate',
    GetWorkCalendarTemplate: '/Team/GetWorkCalendarTemplate?',
    DeleteWorkCalendarTemplate: '/Team/DeleteWorkCalendarTemplate?',
    UpdateWorkCalendarTemplate: '/Team/UpdateWorkCalendarTemplate?',
    GetWeekDays: '/Team/GetWeekDays',
    InsertWorkCalendarTemplate: '/Team/InsertWorkCalendarTemplate?',
    GenerateWorkCalendar: '/Team/GenerateWorkCalendar?',
    SaveAndPublish: '/Workflow/SaveAndPublish',
    ValidateBPMNResource: '/Workflow/ValidateBPMNResource',
    GetTeamMembers: '/Team/GetTeamMembers?',
    GetMemberCompliance: '/Team/GetMemberCompliance?',
    GetComplianceItems: '/Team/GetComplianceItems?',
    GetSuspend: '/Team/GetSuspend',
    InsertMemberCompliance: '/Team/InsertMemberCompliance',
    UpdateMemberCompliance: '/Team/UpdateMemberCompliance',
    ValidateCompliance: '/Team/ValidateCompliance?',
    GetApplicants: '/Team/GetApplicants',
    InsertApplicant: '/Team/InsertApplicant',
    UpdateApplicant: '/Team/UpdateApplicant',
    DeleteApplicant: '/Team/DeleteApplicant?',
    AttachApplicant: '/Team/AttachApplicant?',
    GetAllEventForDesigner: '/Event/GetAllForDesigner',
    GetTaskByEventId: '/Task/GetByEventId?',
    GetFreeTeamMembers: '/Team/GetFreeTeamMembers?',
    UpdateTeamMembers: '/Team/UpdateTeamMembers?',
    DeleteTeamMember: '/Team/DeleteTeamMember?',
    AttachMember: '/Team/AttachMember?',
    GetMemberType: '/Team/GetMemberType',
    GetContractDetailHistory: '/Team/GetContractDetailHistory?',
    TeamApprove: '/Team/TeamApprove?',
    TeamActivate: '/Team/TeamActivate?',
    TeamDeactivate: '/Team/TeamDeactivate?',
    StartSendEmailSMSToAll: '/workflow/StartSendEmailSMSToAll',
    DeleteWorkTeamSkill: '/Team/DeleteWorkTeamSkill?',
    InsertWorkTeamSkill: '/Team/InsertWorkTeamSkill',
    GetApplicantType: '/Team/GetApplicantType',
    GetApprovedOpenings: '/Team/GetApprovedOpenings',
    InterviewApplicant: '/Team/InterviewApplicant?',
    AcceptApplicant: '/Team/AcceptApplicant?',
    ApproveApplicant: '/Team/ApproveApplicant?',
    HireApplicant: '/Team/HireApplicant?',
    GetOpenings: '/Team/GetOpenings',
    GetActiveOffices: '/Team/GetActiveOffices',
    UpdateOpening: '/Team/UpdateOpening?',
    InsertOpening: '/Team/InsertOpening?',
    DeleteOpening: '/Team/DeleteOpening?',
    ApproveOpening: '/Team/ApproveOpening?',
    ExpireOpening: '/Team/ExpireOpening?',
    GetCustomerScheduleInfo: '/Scheduling/GetCustomerScheduleInfo?',
    GetCustomerAMPM: '/Scheduling/GetCustomerAMPM',
    GetMainServicelines: '/Team/GetMainServicelines?',
    GetOFPParameter: '/Parameter/GetOFPParameter?OFPHeaderId=',
    GetAllParameterCallType: '/Parameter/GetAllCallType',
    GetOpeningsApplicants: '/Team/GetOpeningsApplicants?',
    GetTeamStatus: '/Team/GetTeamStatus',
    RejectApplicant: '/Team/RejectApplicant?',
    SaveParameter: '/Parameter/Save',
    GetUserDefaultValues: '/team/GetUserDefaultValues?',
    CreateApplicantPersonnel: '/Team/CreateApplicantPersonnel?',
    GetPersonnel: '/Team/GetPersonnel?',
    DeletePersonnel: '/Team/DeletePersonnel?',
    ActivatePersonnel: '/Team/ActivatePersonnel?',
    DeactivatePersonnel: '/Team/DeactivatePersonnel?',
    GetWarehouses: '/Team/GetWarehouses',
    GetDepartments: '/Team/GetDepartments',
    GetRegions: '/Team/GetRegions',
    GetPersonnelType: '/Team/GetPersonnelType?',
    GetSegments: '/Team/GetSegments',
    InsertPersonnel: '/Team/InsertPersonnel',
    UpdatePersonnel: '/Team/UpdatePersonnel',
    ValidateTeam: '/Team/ValidateTeam?',
    GetUnAssignToPersonel: '/account/GetUnAssignToPersonel',
    GetTablets: '/Team/GetTablets?',
    InsertTablet: '/Team/InsertTablet?',
    UpdateTablet: '/Team/UpdateTablet?',
    DeleteTablet: '/Team/DeleteTablet?',
    GetTeamTablets: '/Team/GetTeamTablets?',
    InsertTeamTablet: '/Team/InsertTeamTablet?',
    UpdateTeamTablet: '/Team/UpdateTeamTablet?',
    GetTeamsWithoutTablet: '/Team/GetTeamsWithoutTablet?',
    GetLastTabletInfoByPohoneNo: '/Merakli/GetLastTabletInfoByPohoneNo?',
    CopyBaselinesToCurrentContract: '/Team/CopyBaselinesToCurrentContract?',
    GetPersonnelHourRates: '/Team/GetPersonnelHourRates?',
    GetPersonnelPayrolls: '/Team/GetPersonnelPayrolls?',
    InsertPersonnelHourRate: '/Team/InsertPersonnelHourRate?',
    UpdatePersonnelHourRate: '/Team/UpdatePersonnelHourRate?',
    DeletePersonnelHourRate: '/Team/DeletePersonnelHourRate?',
    GetTeamsforCopy: '/Team/GetTeamsforCopy?',
    GetTeamsContractHeaders: '/Team/GetTeamsContractHeaders?',
    GetTeamsContractHeaderLogs: '/Team/GetTeamsContractHeaderLogs?',
    GetPersonnelStatus: '/Team/GetPersonnelStatus',
    GetMemberTeamNo: '/Team/GetMemberTeamNo?',
    GetAllInfoByAccountId: '/Account/GetAllInfoByAccountId?',
    GetAttachments: '/Attachment/GetAttachments?',
    GetExExternalServiceAction: '/Workflow/GetExExternalServiceAction',
    InvokeServiceCall: '/Workflow/InvokeServiceCall?',
    GetMissingOperations: '/Team/GetMissingOperations?',
    GetRealSubsSubledgers: '/Team/GetRealSubsSubledgers',
    GetMissingOperationTypes: '/Team/GetMissingOperationTypes',
    UpdateMissingOperations: '/Team/UpdateMissingOperations?',
    TransferMissingOperations: '/Team/TransferMissingOperations?',
    InsertNewTeamSubledger: '/Team/InsertNewTeamSubledger?',
    GetTeamTagCombo: '/Team/GetTeamTagCombo',
    GetTabletAccounts: '/Team/GetTabletAccounts',
    AssignTeamTablet: '/Team/AssignTeamTablet?',
    UnassignTeamTablet: '/Team/UnassignTeamTablet?',
    BindTeamLeaderToBPMSAccount: '/Team/BindTeamLeaderToBPMSAccount?',
    InsertTabletAccount: '/Team/InsertTabletAccount?',
    UpdateTabletAccount: '/Team/UpdateTabletAccount?',
    DeleteTabletAccount: '/Team/DeleteTabletAccount?',
    GetFreeTeamEmployees: '/Team/GetFreeTeamEmployees?',
    AttachEmployee: '/Team/AttachEmployee?',
    GetTabletStatus: '/Team/GetTabletStatus',
    ApproveAllMissing: '/Team/ApproveAllMissing',
    ApproveAllContracts: '/Team/ApproveAllContracts?',
    DeleteMissingOperations: '/Team/DeleteMissingOperations?',
    InstallerOngoingJobs: '/Team/InstallerOngoingJobs?',
    MoveSubCrewToAnotherSub: '/Team/MoveSubCrewToAnotherSub?',
    CopyTeam: '/Team/CopyTeam?',
    GenerateMissingOperations: '/Team/GenerateMissingOperations?',
    GetMissingOperationHeaders: '/Team/GetMissingOperationHeaders?',
    GetMissingOperationDetails: '/Team/GetMissingOperationDetails?',
    GetPerformanceReportSummary: '/Team/GetPerformanceReportSummary?',
    GetPerformanceReportSummaryOrder: '/Team/GetPerformanceReportSummaryOrder?',
    GetOrderInstallerInfo: '/Team/GetOrderInstallerInfo?',
    GetBasicPriceHeader: '/cst/GetBasicPriceHeader?',
    GetCalendar: '/cst/GetCalendarHeader',
    DeleteBasicPriceHeader: '/cst/DeleteBasicPriceHeader?',
    DeleteCalendar: '/cst/DeleteCalendarHeader?',
    InsertBasicPriceHeader: '/cst/InsertBasicPriceHeader',
    CopySubDomainBaseline: '/cst/CopySubDomainBaseline?',
    InsertCalendarHeader: '/cst/InsertCalendarHeader',
    UpdateCalendarHeader: '/cst/UpdateCalendarHeader',
    UpdateCalendarDetail: '/cst/UpdateCalendarDetail?',
    GetCalendarDetailQuarters: '/cst/GetCalendarDetailQuarters',
    GetCalendarDetail: '/cst/GetCalendarDetail?',
    InsertCalendarDetail: '/cst/InsertCalendarDetail?',
    DeleteCalendarDetail: '/cst/DeleteCalendarDetail?',
    UpdateBasicPriceHeader: '/cst/UpdateBasicPriceHeader',
    GetBasicPriceDetail: '/cst/GetBasicPriceDetail?',
    InsertBasicPriceDetail: '/cst/InsertBasicPriceDetail',
    UpdateBasicPriceDetail: '/cst/UpdateBasicPriceDetail?',
    DeleteBasicPriceDetail: '/cst/DeleteBasicPriceDetail?',
    GetBasicPricePerOperation: '/cst/GetBasicPricePerOperation?',
    GetAllOperations: '/Team/GetAllOperations',
    GetServicelineWithKind: '/cst/GetServicelineWithKind?',
    GetServicelineOperationWithDetail:
      '/cst/GetServicelineOperationWithDetail?',
    InsertOperation: '/cst/InsertOperation',
    UpdateOperation: '/cst/UpdateOperation',
    DeleteOperation: '/cst/DeleteOperation?',
    GetOperationKinds: '/cst/GetOperationKinds',
    GetOperationItems: '/cst/GetOperationItems',
    GetOperationExpenses: '/cst/GetOperationExpenses?',
    GetOperationExpenseInsertList: '/cst/GetOperationExpenseInsertList?',
    GetUnits: '/cst/GetUnits',
    GetInstallerDailyRoute: '/Scheduling/GetInstallerDailyRoute?',
    InsertOperationExpense: '/cst/InsertOperationExpense?',
    UpdateOperationExpense: '/cst/UpdateOperationExpense?',
    DeleteOperationExpense: '/cst/DeleteOperationExpense?',
    GetServicelineKind: '/cst/GetServicelineKind',
    GetOffices: '/cst/GetOffices?',
    GetAllLocations: '/Location/GetAllLocations?',
    GetTaskSubKeyValue: '/task/GetTaskSubKeyValue?',
    SignAttachments: '/Attachment/SignAttachments',
    GetPersonnelResidence: '/Team/GetPersonnelResidence',
    CancelOfPInstance: '/workflow/CancelOfPInstance?',
    GetEventTypes: '/Event/GetEventTypes',
    SaveEvent: '/Event/SaveEvent',
    GetScope: '/Event/GetScope',
    GetEvent: '/Event/GetEvent?',
    GetCheckList: '/Event/GetCheckList',
    DeleteEvent: '/Event/Delete?',
    SaveEventParameter: '/Event/SaveEventParameter',
    Timeing: '/Event/Timeing?',
    GetServiceMaskParameterInEvent:
      '/ServiceMask/GetServiceMaskParameterInEvent?',
    GetEventParameterList: '/Event/GetEventParameter?',
    SaveEventActionParameterModel: '/Event/SaveEventActionParameterModel',
    ResetPatametrMapping: '/Event/ResetPatametrMapping?',
    DeleteEventParameter: '/Event/DeleteEventParameter?',
    GetAllConnection: '/Connection/GetAll',
    SaveConnection: '/Connection/Save',
    GetLastLogin: '/account/GetLastLogin?',
    GetAllActivity: '/account/GetAllActivity?',
    ServicelineMethod: {
      GetServicelineMethods: '/cst/GetServicelineMethods?',
      GetMethodItemCategory: '/cst/GetMethodItemCategory',
      GetMethodSubledger: '/cst/GetMethodSubledger',
      GetMethodValidity: '/cst/GetMethodValidity',
      UpdateServicelineMethod: '/cst/UpdateServicelineMethod',
      InsertServicelineMethod: '/cst/InsertServicelineMethod',
      DeleteServicelineMethod: '/cst/DeleteServicelineMethod?',
    },
    MethodExpenses: {
      GetMethodExpenses: '/cst/GetMethodExpenses?',
      GetMethodExpenseInsertList: '/cst/GetMethodExpenseInsertList?',
      InsertMethodExpense: '/cst/InsertMethodExpense?',
      UpdateMethodExpense: '/cst/UpdateMethodExpense?',
      DeleteMethodExpense: '/cst/DeleteMethodExpense?',
      CopyMethodExpenses: '/cst/CopyMethodExpenses?',
    },
    MethodSPD: {
      GetMethodSPDs: '/cst/GetMethodSPDs?',
      GetSPDOperation: '/cst/GetSPDOperation?',
      GetSPDOriginalOperation: '/cst/GetSPDOriginalOperation?',
      GetSPDType: '/cst/GetSPDType',
      InsertSPD: '/cst/InsertSPD',
      UpdateSPD: '/cst/UpdateSPD',
      DeleteSPD: '/cst/DeleteSPD?',
    },
    ApplicantCompliance: {
      GetApplicantCompliance: '/Team/GetApplicantCompliance?',
      GetApplicantComplianceItems: '/Team/GetApplicantComplianceItems',
      InsertApplicantCompliance: '/Team/InsertApplicantCompliance',
    },
    PersonnelCompliance: {
      GetPersonnelCompliance: '/Team/GetPersonnelCompliance?',
      GetPersonnelComplianceItems: '/Team/GetPersonnelComplianceItems',
      InsertPersonnelCompliance: '/Team/InsertPersonnelCompliance',
    },
    ProcessRequirement: {
      GetMethodPRs: '/cst/GetMethodPRs?',
      GetCategoryItems: '/cst/GetCategoryItems?',
      InsertMethodPRs: '/cst/InsertMethodPRs',
      UpdateMethodPRs: '/cst/UpdateMethodPRs',
      DeleteMethodPRs: '/cst/DeleteMethodPRs?',
    },
    ComplianceDefinition: {
      GetComplianceDefinition: '/cst/GetComplianceDefinition',
      GetComplianceDefinitionTarget: '/cst/GetComplianceDefinitionTarget',
      GetComplianceDefinitionScope: '/cst/GetComplianceDefinitionScope?',
      GetComplianceDefinitionRule: '/cst/GetComplianceDefinitionRule',
      InsertComplianceDefinition: '/cst/InsertComplianceDefinition',
      UpdateComplianceDefinition: '/cst/UpdateComplianceDefinition',
      DeleteComplianceDefinition: '/cst/DeleteComplianceDefinition?',
    },
    ComplianceAttachments: {
      GetComplianceAttachments: '/cst/GetComplianceAttachments?',
      GetComplianceAttachmentCombo: '/cst/GetComplianceAttachmentCombo',
      GetComplianceAttchmentMandatory: '/cst/GetComplianceAttchmentMandatory',
      InsertComplianceAttachment: '/cst/InsertComplianceAttachment',
      UpdateComplianceAttachment: '/cst/UpdateComplianceAttachment',
      DeleteComplianceAttachment: '/cst/DeleteComplianceAttachment?',
    },
    MethodAttachmentRules: {
      GetMethodAttachmentRules: '/cst/GetMethodAttachmentRules?',
      GetSignature: '/cst/GetSignature',
      GetAttachments: '/cst/GetAttachments',
      GetOldOrderStatus: '/cst/GetOldOrderStatus',
      InsertMethodAttachmentRules: '/cst/InsertMethodAttachmentRules',
      UpdateMethodAttachmentRules: '/cst/UpdateMethodAttachmentRules',
      DeleteMethodAttachmentRules: '/cst/DeleteMethodAttachmentRules?',
    },
    SubManagement: {
      GetAllSubs: '/cst/GetAllSubs?',
      GetSubActCombo: '/cst/GetSubActCombo',
      InsertSub: '/cst/InsertSub?',
      UpdateSub: '/cst/UpdateSub?',
      DeleteSub: '/cst/DeleteSub?',
      ActivateSub: '/cst/ActivateSub?',
      DeactivateSub: '/cst/DeactivateSub?',
      GetSubCompliance: '/Team/GetSubCompliance?',
      GetSubComplianceItems: '/Team/GetSubComplianceItems',
      InsertSubCompliance: '/Team/InsertSubCompliance',
      GetSubPersonnel: '/cst/GetSubPersonnel',
    },
    ProcessFinancesFormulas: {
      GetMethodPFFs: '/cst/GetMethodPFFs?',
      GetMethodPFFLedgers: '/cst/GetMethodPFFLedgers',
      GetMethodPFFGroups: '/cst/GetMethodPFFGroups',
      GetMethodPFFTypes: '/cst/GetMethodPFFTypes',
      GetMethodPFFCalculations: '/cst/GetMethodPFFCalculations',
      GetMethodPFFApplications: '/cst/GetMethodPFFApplications',
      InsertMethodPFF: '/cst/InsertMethodPFF',
      UpdateMethodPFF: '/cst/UpdateMethodPFF',
      DeletePFF: '/cst/DeletePFF?',
      GetFinanceFormulas: '/cst/GetFinanceFormulas?',
      GetFinanceFormulasSigns: '/cst/GetFinanceFormulasSigns',
      InsertFinanceFormula: '/cst/InsertFinanceFormula',
      UpdateFinanceFormula: '/cst/UpdateFinanceFormula',
      DeleteFinanceFormula: '/cst/DeleteFinanceFormula?',
    },
    MarketsAndStores: {
      GetMarkets: '/cst/GetMarkets?',
      InsertMarket: '/cst/InsertMarket',
      UpdateMarket: '/cst/UpdateMarket',
      DeleteMarket: '/cst/DeleteMarket?',
      GetStores: '/cst/GetStores?',
      GetCities: '/cst/GetCities',
      InsertStore: '/cst/InsertStore',
      UpdateStore: '/cst/UpdateStore',
      DeleteStore: '/cst/DeleteStore?',
      GetStorePersons: '/cst/GetStorePersons?',
      GetStorePersonBilling: '/cst/GetStorePersonBilling',
      GetStorePersonReport: '/cst/GetStorePersonReport',
      GetStorePersonType: '/cst/GetStorePersonType',
      InsertStorePerson: '/cst/InsertStorePerson',
      UpdateStorePerson: '/cst/UpdateStorePerson',
      DeleteStorePerson: '/cst/DeleteStorePerson?',
      GetStorePhones: '/cst/GetStorePhones?',
      GetPhoneTypes: '/cst/GetPhoneTypes',
      InsertStorePhone: '/cst/InsertStorePhone',
      UpdateStorePhone: '/cst/UpdateStorePhone',
      DeleteStorePhone: '/cst/DeleteStorePhone?',
      GetMarketInstallationPrograms: '/cst/GetMarketInstallationPrograms?',
      InsertMarketInstallationProgram: '/cst/InsertMarketInstallationProgram',
      UpdateMarketInstallationProgram: '/cst/UpdateMarketInstallationProgram',
      DeleteMarketInstallationProgram: '/cst/DeleteMarketInstallationProgram?',
      ValidateMarketInstallationProgram:
        '/cst/ValidateMarketInstallationProgram?',
      ExpireMarketInstallationProgram: '/cst/ExpireMarketInstallationProgram?',
      GetMarketLaborPrices: '/cst/GetMarketLaborPrices?',
      GetServicelineMethodOperations: '/cst/GetServicelineMethodOperations?',
      GetMarketLaborKind: '/cst/GetMarketLaborKind',
      InsertMarketLaborPrice: '/cst/InsertMarketLaborPrice',
      UpdateMarketLaborPrice: '/cst/UpdateMarketLaborPrice',
      DeleteMarketLaborPrice: '/cst/DeleteMarketLaborPrice?',
      GetMarketMaterialPrices: '/cst/GetMarketMaterialPrices?',
      GetInventoryItems: '/cst/GetInventoryItems',
      InsertMarketMatPrice: '/cst/InsertMarketMatPrice',
      UpdateMarketMatPrice: '/cst/UpdateMarketMatPrice',
      DeleteMarketMatPrice: '/cst/DeleteMarketMatPrice?',
      GetStoreVisits: '/cst/GetStoreVisits?',
      CreateStoreVisitOrder: '/cst/CreateStoreVisitOrder?',
      GetStoreSubledgers: '/cst/GetStoreSubledgers',
      TransferTarifFromInstallationProgram:
        '/cst/TransferTarifFromInstallationProgram?',
      CopyTarifToMarket: '/cst/CopyTarifToMarket?',
    },

    GridColumnDef: {
      Save: '/GridColumnDef/Save',
      Get: '/GridColumnDef/Get',
    },

    ProcessManagement: {
      GetWorkflkowInstance: '/Workflow/GetWorkflkowInstance',
      GetWorkflkowInstanceStatus: '/Workflow/GetWorkflkowInstanceStatus',
    },
    StatementManagement: {
      GetSttDirections: '/RAP/GetSttDirections',
      GetSttSources: '/RAP/GetSttSources?',
      GetStatementsHeaders: '/RAP/GetStatementsHeaders?',
      GetSubledger: '/Team/GetSubledger?',
      GetSttStatuses: '/RAP/GetSttStatuses',
      InsertStatementsHeader: '/RAP/InsertStatementsHeader',
      UpdateStatementsHeader: '/RAP/UpdateStatementsHeader',
      DeleteStatementsHeader: '/RAP/DeleteStatementsHeader?',
      ConfirmStatementsHeader: '/RAP/ConfirmStatementsHeader?',
      ApproveStatementsHeader: '/RAP/ApproveStatementsHeader?',
      GetStatementSales: '/RAP/GetStatementSales?',
      GetStatementSaleOrdersList: '/RAP/GetStatementSaleOrdersList?',
      InsertStatementSale: '/RAP/InsertStatementSale?',
      DeleteStatementSale: '/RAP/DeleteStatementSale',
      GetSttPurchases: '/RAP/GetSttPurchases?',
      GetSttPurchasesList: '/RAP/GetSttPurchasesList?',
      InsertSttPurchases: '/RAP/InsertSttPurchases?',
      DeleteSttPurchases: '/RAP/DeleteSttPurchases?',
      GetCashEvents: '/RAP/GetCashEvents?',
      GetCashEventKind: '/RAP/GetCashEventKind?',
      GetCashEventChecksList: '/RAP/GetCashEventChecksList?',
      InsertCashEvent: '/RAP/InsertCashEvent',
      UpdateCashEvent: '/RAP/UpdateCashEvent',
      DeleteCashEvent: '/RAP/DeleteCashEvent?',
      GetSttNotes: '/RAP/GetSttNotes',
      GetSttAccounts: '/RAP/GetSttAccounts',
      GetSttNoteKinds: '/RAP/GetSttNoteKinds',
      GetSttNoteTypes: '/RAP/GetSttNoteTypes',
      GetSttNoteBanks: '/RAP/GetSttNoteBanks',
      InsertSttNote: '/RAP/InsertSttNote',
      UpdateSttNote: '/RAP/UpdateSttNote',
      DeleteSttNote: '/RAP/DeleteSttNote?',
      GetPayableOpenItems: '/RAP/GetPayableOpenItems?',
      GetPayableOpenItemTypes: '/RAP/GetPayableOpenItemTypes',
      InsertPayableOpenItems: '/RAP/InsertPayableOpenItems',
      UpdatePayableOpenItems: '/RAP/UpdatePayableOpenItems',
      DeletePayableOpenItems: '/RAP/DeletePayableOpenItems?',
      GetAROpenItems: '/RAP/GetAROpenItems?',
      GetARopenItemPOList: '/RAP/GetARopenItemPOList',
      GetAROpenItemStatuses: '/RAP/GetAROpenItemStatuses',
      InsertAROpenItem: '/RAP/InsertAROpenItem',
      UpdateAROpenItem: '/RAP/UpdateAROpenItem',
      DeleteAROpenItems: '/RAP/DeleteAROpenItems?',
      GetOpenLogs: '/RAP/GetOpenLogs?',
      PushToLog: '/RAP/PushToLog?',
      OpenARPushToLog: '/RAP/OpenARPushToLog?',
      PushAllAROpenItemsToLog: '/RAP/PushAllAROpenItemsToLog?',
      UnconfirmStatementsHeader: '/RAP/UnconfirmStatementsHeader?',
      TransferOpenItems: '/RAP/TransferOpenItems?',
      ImportLastHDCheck: '/RAP/ImportLastHDCheck?',
      GenerateStatements: '/RAP/GenerateStatements',
      DeleteAllStatementItems: '/RAP/DeleteAllStatementItems?',
      GetStatementExpenses: '/RAP/GetStatementExpenses?',
      GetStatementExpensesList: '/RAP/GetStatementExpensesList?',
      InsertStatementExpense: '/RAP/InsertStatementExpense?',
      DeleteStatementExpense: '/RAP/DeleteStatementExpense?',
      QuickBookExport: '/RAP/QuickBookExport?',
      GetLastFileIdByType: '/OrderAttachment/GetLastFileIdByType?',
      GetStatementPDFList: '/RAP/GetStatementPDFList',
      GetAllAPOpenItems: '/RAP/GetAllAPOpenItems?',
    },
    VOC: {
      GetVOCHeader: '/RAP/GetVOCHeader?',
      GetVOCDetail: '/RAP/GetVOCDetail?',
      ImportLastVOCCSV: '/RAP/ImportLastVOCCSV?',
      GetHDFiscalQuarters: '/RAP/GetHDFiscalQuarters',
      GetAllInstallers: '/RAP/GetAllInstallers',
      VOCNavigate: '/RAP/VOCNavigate?',
      GetVOCGraph: '/RAP/GetVOCGraph?',
      GetVOCImportHeader: '/RAP/GetVOCImportHeader',
    },
    Reconcile: {
      GetReconciles: '/RAP/GetReconciles?',
      GetReconcileStatuses: '/RAP/GetReconcileStatuses',
      GetReconcileTypes: '/RAP/GetReconcileTypes',
      GetReconcileClasses: '/RAP/GetReconcileClasses?',
      InsertReconcile: '/RAP/InsertReconcile',
      UpdateReconcile: '/RAP/UpdateReconcile',
      DeleteReconcile: '/RAP/DeleteReconcile?',
      AddAllMatchedItems: '/RAP/AddAllMatchedItems?',
      GetReconcileAROpenItems: '/RAP/GetReconcileAROpenItems?',
      GetReconcileAROpenItemList: '/RAP/GetReconcileAROpenItemList?',
      InsertReconcileARopenItem: '/RAP/InsertReconcileARopenItem?',
      DeleteReconcileARopenItem: '/RAP/DeleteReconcileARopenItem?',
      GetReconcileAPOpenItems: '/RAP/GetReconcileAPOpenItems?',
      GetReconcileAPOpenItemList: '/RAP/GetReconcileAPOpenItemList?',
      InsertReconcileAPopenItem: '/RAP/InsertReconcileAPopenItem?',
      DeleteReconcileAPopenItem: '/RAP/DeleteReconcileAPopenItem?',
      GetReconcileSalesBills: '/RAP/GetReconcileSalesBills?',
      GetReconcileSalesBillsList: '/RAP/GetReconcileSalesBillsList?',
      InsertReconcileSaleBill: '/RAP/InsertReconcileSaleBill',
      DeleteReconcileSaleBill: '/RAP/DeleteReconcileSaleBill?',
      GetReconcilePurchase: '/RAP/GetReconcilePurchase?',
      GetReconcilePurchaseList: '/RAP/GetReconcilePurchaseList?',
      InsertReconcilePurchase: '/RAP/InsertReconcilePurchase?',
      DeleteReconcilePurchase: '/RAP/DeleteReconcilePurchase?',
      GetReconcileExpense: '/RAP/GetReconcileExpense?',
      GetReconcileExpenseList: '/RAP/GetReconcileExpenseList?',
      InsertReconcileExpense: '/RAP/InsertReconcileExpense?',
      DeleteReconcileExpense: '/RAP/DeleteReconcileExpense?',
      GetReconcileAdjFinance: '/RAP/GetReconcileAdjFinance',
      GetReconcileAdjValues: '/RAP/GetReconcileAdjValues?',
      InsertReconcileAdj: '/RAP/InsertReconcileAdj?',
      ConfirmReconcile: '/RAP/ConfirmReconcile?',
      UnconfirmReconcile: '/RAP/UnconfirmReconcile?',
    },
    Payroll: {
      GetPayrollHeader: '/RAP/GetPayrollHeader?',
      GetPayrollStatus: '/RAP/GetPayrollStatus',
      GetPayrollCurrentStatus: '/RAP/GetPayrollCurrentStatus',
      GetPayrollsCombo: '/RAP/GetPayrollsCombo',
      ImportLastNovatimeFiles: '/RAP/ImportLastNovatimeFiles?',
      CalculatePayroll: '/RAP/CalculatePayroll?',
      ConfirmPayroll: '/RAP/ConfirmPayroll?',
      ExportPayroll: '/RAP/ExportPayroll?',
      GetPayrollSubledgers: '/RAP/GetPayrollSubledgers?',
      GetPayrollsBudgetRates: '/RAP/GetPayrollsBudgetRates?',
      GetPayrollsBudgetRateList: '/RAP/GetPayrollsBudgetRateList?',
      InsertPayrollBudgetRates: '/RAP/InsertPayrollBudgetRates?',
      DeletePayrollBudgetRates: '/RAP/DeletePayrollBudgetRates?',
      GetPayrollAdjustmentList: '/RAP/GetPayrollAdjustmentList',
      MovePayrollAdjustment: '/RAP/MovePayrollAdjustment?',
      GetPayrollsPerformance: '/RAP/GetPayrollsPerformance?',
      InsertPayrollPerformance: '/RAP/InsertPayrollPerformance?',
      DeletePayrollPerformance: '/RAP/DeletePayrollPerformance?',
      GetPayrollsInvoiceExpenses: '/RAP/GetPayrollsInvoiceExpenses?',
      GetPayrollsInvoiceExpensesList: '/RAP/GetPayrollsInvoiceExpensesList?',
      InsertPayrollInvoiceExpenses: '/RAP/InsertPayrollInvoiceExpenses?',
      DeletePayrollInvoiceExpenses: '/RAP/DeletePayrollInvoiceExpenses?',
      GetPayrollsOrderExpenses: '/RAP/GetPayrollsOrderExpenses?',
      GetPayrollsAttendance: '/RAP/GetPayrollsAttendance?',
      GetPayrollsCalculatedItems: '/RAP/GetPayrollsCalculatedItems?',
      GetLastPayrollExport: '/RAP/GetLastPayrollExport?',
      GetPayrollPDFList: '/RAP/GetPayrollPDFList',
      GetPayrollVOC: '/RAP/GetPayrollVOC?',
      AdjustPayrollInvoiceExpenses: '/RAP/AdjustPayrollInvoiceExpenses?',
      AdjustPayrollOrderExpenses: '/RAP/AdjustPayrollOrderExpenses?',
      ImportAndCalculateRetroFiles: '/RAP/ImportAndCalculateRetroFiles?',
      DeletePayrollClcRetro: '/RAP/DeletePayrollClcRetro?',
      GetPayrollsRetroCalculatedItems: '/RAP/GetPayrollsRetroCalculatedItems?',
    },
    Enterance: {
      GetEntranceHeader: '/Inventory/GetEntranceHeader?',
      GetEntranceKind: '/Inventory/GetEntranceKind',
      InsertEntranceHeader: '/Inventory/InsertEntranceHeader',
      UpdateEntranceHeader: '/Inventory/UpdateEntranceHeader',
      DeleteEntranceHeader: '/Inventory/DeleteEntranceHeader?',
      GetLocation: '/OrderProcessing/GetLocation',
      GetEntranceDetail: '/Inventory/GetEntranceDetail?',
      GetEntranceMills: '/Inventory/GetEntranceMills',
      GetEntranceDetailDefaults: '/Inventory/GetEntranceDetailDefaults?',
      EntranceDetailPositionChanged:
        '/Inventory/EntranceDetailPositionChanged?',
      InsertEntranceDetail: '/Inventory/InsertEntranceDetail',
      UpdateEntranceDetail: '/Inventory/UpdateEntranceDetail',
      DeleteEntranceDetail: '/Inventory/DeleteEntranceDetail?',
    },
    Exit: {
      GetExitHeader: '/Inventory/GetExitHeader?',
      GetExitStatus: '/Inventory/GetExitStatus',
      InsertExitHeader: '/Inventory/InsertExitHeader',
      UpdateExitHeader: '/Inventory/UpdateExitHeader',
      DeleteExitHeader: '/Inventory/DeleteExitHeader?',
      GetExitDetail: '/Inventory/GetExitDetail?',
      InsertExitDetail: '/Inventory/InsertExitDetail?',
    },
    BillOfLading: {
      GetBOL: '/Inventory/GetBOL?',
      GetBOLLocations: '/Inventory/GetBOLLocations',
      UpdateBOL: '/Inventory/UpdateBOL?',
    },
    MaterialConfirmation: {
      GetMatConfDispatchList: '/Inventory/GetMatConfDispatchList?',
      GetMatConfReviseCancelOrderList:
        '/Inventory/GetMatConfReviseCancelOrderList?',
    },
    Counting: {
      GetCountingHeader: '/Inventory/GetCountingHeader?',
      GetCountingHeaderStatus: '/Inventory/GetCountingHeaderStatus',
      GetItemCategory: '/Inventory/GetItemCategory',
      GetInternalItemCategory: '/Inventory/GetInternalItemCategory?',
      InsertCountingHeader: '/Inventory/InsertCountingHeader',
      UpdateCountingHeader: '/Inventory/UpdateCountingHeader',
      DeleteCountingHeader: '/Inventory/DeleteCountingHeader?',
      CommitCountingHeader: '/Inventory/CommitCountingHeader?',
      RecalculateCountingHeader: '/Inventory/RecalculateCountingHeader?',
      GetCountingDetail: '/Inventory/GetCountingDetail?',
      GetCountingDetailDefaultValues:
        '/Inventory/GetCountingDetailDefaultValues?',
      GetCountingDetailBORList: '/Inventory/GetCountingDetailBORList?',
      InsertCountingDetail: '/Inventory/InsertCountingDetail',
      UpdateCountingDetail: '/Inventory/UpdateCountingDetail?',
      DeleteCountingDetail: '/Inventory/DeleteCountingDetail?',
      CountingDiscrepancy:
        '/frmDisplaySSRSreport.aspx?path=/CP Reports/Inventory/Counting Discrepancy&hp=',
    },
    Correction: {
      GetCorrectionHeader: '/Inventory/GetCorrectionHeader?',
      GetCorrectionEntrance: '/Inventory/GetCorrectionEntrance?',
      GetCorrectionExit: '/Inventory/GetCorrectionExit?',
      GetCorrectionEntered: '/Inventory/GetCorrectionEntered?',
      GetCorrectionExited: '/Inventory/GetCorrectionExited?',
      GetCorrectionRepalced: '/Inventory/GetCorrectionRepalced?',
      GetCorrectionHeaderStatus: '/Inventory/GetCorrectionHeaderStatus',
      GetCorrectionHeaderType: '/Inventory/GetCorrectionHeaderType?',
      ConfrimCorrection: '/Inventory/ConfrimCorrection?',
      ToBeReplaceBORList: '/Inventory/ToBeReplaceBORList?',
      ToBeReplaceInsert: '/Inventory/ToBeReplaceInsert?',
      ToBeReplaceUpdate: '/Inventory/ToBeReplaceUpdate?',
      ToBeReplaceDelete: '/Inventory/ToBeReplaceDelete?',
      AutoCollectWaste: '/Inventory/AutoCollectWaste?',
      InsertCorrection: '/Inventory/InsertCorrection',
    },
    Purchase: {
      GetPurchaseHeader: '/Purchase/GetPurchaseHeader?',
      GetPurchaseHeaderStatus: '/Purchase/GetPurchaseHeaderStatus',
      GetPurchaseMethodsCombo: '/Purchase/GetPurchaseMethodsCombo',
      GetPurchaseVendorsList: '/Purchase/GetPurchaseVendorsList',
      InsertPurchaseHeader: '/Purchase/InsertPurchaseHeader',
      UpdatePurchaseHeader: '/Purchase/UpdatePurchaseHeader',
      DeletePurchaseHeader: '/Purchase/DeletePurchaseHeader?',
      SubmitPurchaseHeader: '/Purchase/SubmitPurchaseHeader?',
      ReceivedPrefectPurchaseHeader: '/Purchase/ReceivedPrefectPurchaseHeader?',
      CancelPurchaseHeader: '/Purchase/CancelPurchaseHeader?',
      UnconfirmPurchaseHeader: '/Purchase/UnconfirmPurchaseHeader?',
      PaidPurchaseHeader: '/Purchase/PaidPurchaseHeader?',
      GetPurchaseRequests: '/Purchase/GetPurchaseRequests?',
      GetPurchaseRequestItemList: '/Purchase/GetPurchaseRequestItemList?',
      InsertPurchaseRequest: '/Purchase/InsertPurchaseRequest',
      UpdatePurchaseRequest: '/Purchase/UpdatePurchaseRequest?',
      DeletePurchaseRequest: '/Purchase/DeletePurchaseRequest?',
      GetPurchaseMaterialReceive: '/Purchase/GetPurchaseMaterialReceive?',
      GetPurchaseMaterialReceiveEntranceList:
        '/Purchase/GetPurchaseMaterialReceiveEntranceList',
      InsertPurchaseMaterialReceive: '/Purchase/InsertPurchaseMaterialReceive?',
      UpdatePurchaseMaterialReceive: '/Purchase/UpdatePurchaseMaterialReceive?',
      DeletePurchaseMaterialReceive: '/Purchase/DeletePurchaseMaterialReceive?',
      ReturnPurchaseMaterialReceive: '/Purchase/ReturnPurchaseMaterialReceive?',
      GetPurchaseAccountPayable: '/Purchase/GetPurchaseAccountPayable?',
      DeletePurchaseAccountPayable: '/Purchase/DeletePurchaseAccountPayable?',
      RefreshAPPurchaseHeader: '/Purchase/RefreshAPPurchaseHeader?',
      GetPurchaseStandardPrice: '/Purchase/GetPurchaseStandardPrice?',
      GetPurchaseEstimateHeader: '/Purchase/GetPurchaseEstimateHeader?',
      InsertPurchaseEstimateHeader: '/Purchase/InsertPurchaseEstimateHeader?',
      UpdatePurchaseEstimateHeader: '/Purchase/UpdatePurchaseEstimateHeader?',
      DeletePurchaseEstimateHeader: '/Purchase/DeletePurchaseEstimateHeader?',
      GetPurchaseEstimateDetail: '/Purchase/GetPurchaseEstimateDetail?',
      UpdatePurchaseEstimateDetail: '/Purchase/UpdatePurchaseEstimateDetail?',
      DeletePurchaseEstimateDetail: '/Purchase/DeletePurchaseEstimateDetail?',
      PurchaseEstimateDetailCreatePo:
        '/Purchase/PurchaseEstimateDetailCreatePo?',
      EstimatePurchaseDetail: '/Purchase/EstimatePurchaseDetail?',
      GetPurchasableItemHeader: '/Purchase/GetPurchasableItemHeader?',
      UpdatePurchasableItemHeader: '/Purchase/UpdatePurchasableItemHeader?',
      GetPurchasableItems: '/Purchase/GetPurchasableItems?',
      InsertPurchasableItem: '/Purchase/InsertPurchasableItem?',
      UpdatePurchasableItem: '/Purchase/UpdatePurchasableItem?',
      DeletePurchasableItem: '/Purchase/DeletePurchasableItem?',
      GetPurchasableItemPrice: '/Purchase/GetPurchasableItemPrice?',
      GetPurchasableItemPriceDefaultDate:
        '/Purchase/GetPurchasableItemPriceDefaultDate?',
      GetPurchasableItemPriceApplyChange:
        '/Purchase/GetPurchasableItemPriceApplyChange?',
      GetVendor: '/Purchase/GetVendor?',
      InsertVendor: '/Purchase/InsertVendor',
      UpdateVendor: '/Purchase/UpdateVendor',
      DeleteVendor: '/Purchase/DeleteVendor?',
      GetVendorAgent: '/Purchase/GetVendorAgent?',
      InsertVendorAgent: '/Purchase/InsertVendorAgent',
      UpdateVendorAgent: '/Purchase/UpdateVendorAgent',
      DeleteVendorAgent: '/Purchase/DeleteVendorAgent?',
      GetVendorAccount: '/Purchase/GetVendorAccount?',
      InsertVendorAccount: '/Purchase/InsertVendorAccount',
      UpdateVendorAccount: '/Purchase/UpdateVendorAccount',
      DeleteVendorAccount: '/Purchase/DeleteVendorAccount?',
      GetVendorDelivery: '/Purchase/GetVendorDelivery?',
      InsertVendorDelivery: '/Purchase/InsertVendorDelivery',
      UpdateVendorDelivery: '/Purchase/UpdateVendorDelivery',
      DeleteVendorDelivery: '/Purchase/DeleteVendorDelivery?',
      GetVendorItems: '/Purchase/GetVendorItems?',
      InsertVendorItem: '/Purchase/InsertVendorItem',
      UpdateVendorItem: '/Purchase/UpdateVendorItem',
      DeleteVendorItem: '/Purchase/DeleteVendorItem?',
    },
    SubledgerManagement: {
      GetSubledgersData: '/Team/GetSubledgersData?',
      GetSubledgerGroups: '/Team/GetSubledgerGroups',
      GetSubledgerStatus: '/Team/GetSubledgerStatus',
      InsertSubledgerData: '/Team/InsertSubledgerData',
      UpdateSubledgerData: '/Team/UpdateSubledgerData',
      DeleteSubledgerData: '/Team/DeleteSubledgerData?',
    },
    ExpenseDefinitions: {
      GetExpenseDefinitions: '/RAP/GetExpenseDefinitions?',
      GetExpenseDefTypes: '/RAP/GetExpenseDefTypes',
      GetExpenseDefTarget: '/RAP/GetExpenseDefTarget',
      GetExpenseDefAmount: '/RAP/GetExpenseDefAmount',
      GetExpenseDefBasedOn: '/RAP/GetExpenseDefBasedOn',
      GetExpenseDefProvider: '/RAP/GetExpenseDefProvider',
      GetExpenseDefCompensation: '/RAP/GetExpenseDefCompensation',
      InsertExpenseDefinition: '/RAP/InsertExpenseDefinition',
      UpdateExpenseDefinition: '/RAP/UpdateExpenseDefinition',
      DeleteExpenseDefinition: '/RAP/DeleteExpenseDefinition?',
      GetInsertExpenseDefinitionDef: '/RAP/GetInsertExpenseDefinitionDef',
    },
    MaterialCosts: {
      GetMaterialCostsHeader: '/Inventory/GetMaterialCostsHeader?',
      GetMaterialCostsDetail: '/Inventory/GetMaterialCostsDetail?',
      GetMaterialCostsDetailChangeDefault:
        '/Inventory/GetMaterialCostsDetailChangeDefault?',
      MaterialCostsDetailChange: '/Inventory/MaterialCostsDetailChange?',
      GetCostsChangeDocuments: '/Inventory/GetCostsChangeDocuments?',
      InsertCostsChangeDocument: '/Inventory/InsertCostsChangeDocument',
      UpdateCostsChangeDocument: '/Inventory/UpdateCostsChangeDocument',
      DeleteCostsChangeDocument: '/Inventory/DeleteCostsChangeDocument?',
      ApproveCostsChangeDocument: '/Inventory/ApproveCostsChangeDocument?',
      GetCostChangeDocStatus: '/Inventory/GetCostChangeDocStatus',
      GetCostsChangeDocumentDetail: '/Inventory/GetCostsChangeDocumentDetail?',
      GetCostsItems: '/Inventory/GetCostsItems',
      InsertCostsChangeDocumentDetail:
        '/Inventory/InsertCostsChangeDocumentDetail',
      UpdateCostsChangeDocumentDetail:
        '/Inventory/UpdateCostsChangeDocumentDetail',
      DeleteCostsChangeDocumentDetail:
        '/Inventory/DeleteCostsChangeDocumentDetail?',
    },
    TagsDefinition: {
      GetTagsDefinition: '/cst/GetTagsDefinition?',
      GetTagsPattern: '/cst/GetTagsPattern',
      GetTagsScope: '/cst/GetTagsScope',
      GetTagsEvaluation: '/cst/GetTagsEvaluation',
      InsertTagsDefinition: '/cst/InsertTagsDefinition',
      UpdateTagsDefinition: '/cst/UpdateTagsDefinition',
      DeleteTagsDefinition: '/cst/DeleteTagsDefinition?',
    },
    SubAssignment: {
      GetSubAssignmentGrid: '/Scheduling/GetSubAssignmentGrid?',
      GetAssignementSubs: '/Scheduling/GetAssignementSubs?',
      GetSubAssignmentCalendar: '/Scheduling/GetSubAssignmentCalendar?',
      GetAssignementSubsSwitch: '/Scheduling/GetAssignementSubsSwitch?',
      GetAddDayDefaultDate: '/Scheduling/GetAddDayDefaultDate?',
    },
    OfficeManagement: {
      GetCostCenters: '/cst/GetCostCenters',
      GetStates: '/cst/GetStates',
      GetOfficeStatus: '/cst/GetOfficeStatus',
      InsertOffice: '/cst/InsertOffice',
      UpdateOffice: '/cst/UpdateOffice',
      DeleteOffice: '/cst/DeleteOffice?',
      GetOfficeDomains: '/cst/GetOfficeDomains?',
      InsertOfficeDomain: '/cst/InsertOfficeDomain?',
      UpdateOfficeDomain: '/cst/UpdateOfficeDomain?',
      DeleteOfficeDomain: '/cst/DeleteOfficeDomain?',
      GetDomainExpenses: '/cst/GetDomainExpenses?',
      GetDomainExpenseInsertList: '/cst/GetDomainExpenseInsertList?',
      InsertDomainExpense: '/cst/InsertDomainExpense?',
      UpdateDomainExpense: '/cst/UpdateDomainExpense?',
      DeleteDomainExpense: '/cst/DeleteDomainExpense?',
    },
    UnfinishedJobs: {
      GetUnfinishedJobs: '/RAP/GetUnfinishedJobs?',
      GetUnfinishedJobsOrderTypes: '/RAP/GetUnfinishedJobsOrderTypes',
    },
    ChecklistAnswers: {
      GetChecklistAnswersDefinition: '/cst/GetChecklistAnswersDefinition',
      InsertChecklistAnswersDefinition:
        '/cst/InsertChecklistAnswersDefinition?',
      UpdateChecklistAnswersDefinition:
        '/cst/UpdateChecklistAnswersDefinition?',
      DeleteChecklistAnswersDefinition:
        '/cst/DeleteChecklistAnswersDefinition?',
      GetChecklistAnswersDefinitionDetail:
        '/cst/GetChecklistAnswersDefinitionDetail?',
      InsertChecklistAnswersDefinitionDetail:
        '/cst/InsertChecklistAnswersDefinitionDetail?',
      UpdateChecklistAnswersDefinitionDetail:
        '/cst/UpdateChecklistAnswersDefinitionDetail?',
      DeleteChecklistAnswersDefinitionDetail:
        '/cst/DeleteChecklistAnswersDefinitionDetail?',
    },
    ChecklistManagement: {
      GetChecklistDefinitionHeader: '/cst/GetChecklistDefinitionHeader?',
      GetChecklistDefinitionTypes: '/cst/GetChecklistDefinitionTypes',
      InsertChecklistDefinitionHeader: '/cst/InsertChecklistDefinitionHeader',
      UpdateChecklistDefinitionHeader: '/cst/UpdateChecklistDefinitionHeader',
      DeleteChecklistDefinitionHeader: '/cst/DeleteChecklistDefinitionHeader?',
      ValidateChecklistDefinitionHeader:
        '/cst/ValidateChecklistDefinitionHeader?',
      GetChecklistDefinitionStatuses: '/cst/GetChecklistDefinitionStatuses',
      GetChecklistDefinitionDetail: '/cst/GetChecklistDefinitionDetail?',
      GetChecklistDefinitionDetailTypes:
        '/cst/GetChecklistDefinitionDetailTypes',
      GetChecklistDefinitionDetailSources:
        '/cst/GetChecklistDefinitionDetailSources',
      GetChecklistDefinitionDetailAnswers:
        '/cst/GetChecklistDefinitionDetailAnswers',
      InsertChecklistDefinitionDetail: '/cst/InsertChecklistDefinitionDetail',
      UpdateChecklistDefinitionDetail: '/cst/UpdateChecklistDefinitionDetail',
      DeleteChecklistDefinitionDetail: '/cst/DeleteChecklistDefinitionDetail?',
      GetChecklistDefinitionDetailRelations:
        '/cst/GetChecklistDefinitionDetailRelations?',
      GetChecklistDefinitionDetailRelScopeFunctions:
        '/cst/GetChecklistDefinitionDetailRelScopeFunctions?',
      GetChecklistDefinitionDetailRelReferingQuestionList:
        '/cst/GetChecklistDefinitionDetailRelReferingQuestionList',
      GetChecklistDefinitionDetailRelScopes:
        '/cst/GetChecklistDefinitionDetailRelScopes',
      GetChecklistDefinitionDetailRelOperators:
        '/cst/GetChecklistDefinitionDetailRelOperators',
      GetChecklistDefinitionDetailRelIfNotExists:
        '/cst/GetChecklistDefinitionDetailRelIfNotExists',
      InsertChecklistDefinitionDetailRel:
        '/cst/InsertChecklistDefinitionDetailRel',
      UpdateChecklistDefinitionDetailRel:
        '/cst/UpdateChecklistDefinitionDetailRel',
      DeleteChecklistDefinitionDetailRel:
        '/cst/DeleteChecklistDefinitionDetailRel?',
      CopyChecklist: '/cst/CopyChecklist?',
    },
    TimeAndAttendance: {
      GetPunchesHeader: '/RAP/GetPunchesHeader?',
      GetPunchStatuses: '/RAP/GetPunchStatuses',
      GetPunchReasons: '/RAP/GetPunchReasons?',
      InsertPunch: '/RAP/InsertPunch',
      ApprovePunch: '/RAP/ApprovePunch?',
      GetPunchOrders: '/RAP/GetPunchOrders?',
      GetPunchesDetail: '/RAP/GetPunchesDetail?',
      UpdatePunch: '/RAP/UpdatePunch',
      DeletePunch: '/RAP/DeletePunch?',
      GetUserId: '/RAP/GetUserId?',
    },
    OrdersList: {
      GetFlatOrderInfo: '/HomePage/GetFlatOrderInfo?',
    },
    AROpenItems: {
      GetAllAROpenItems: '/RAP/GetAllAROpenItems?',
    },
    InventoryItems: {
      GetInventoryItems: '/Inventory/GetInventoryItems?',
      GetItemsColoring: '/Inventory/GetItemsColoring',
      GetItemsStyle: '/Inventory/GetItemsStyle',
      GetItemProgram: '/Inventory/GetItemProgram',
      GetItemQuality: '/Inventory/GetItemQuality',
      InsertInventoryItem: '/Inventory/InsertInventoryItem',
      UpdateInventoryItem: '/Inventory/UpdateInventoryItem',
      DeleteInventoryItem: '/Inventory/DeleteInventoryItem?',
    },
    ChargebackKindsDefiniton: {
      GetChargebackKindsDefiniton: '/cst/GetChargebackKindsDefiniton',
      GetChargebackFinances: '/cst/GetChargebackFinances',
      GetChargebackKindCalculations: '/cst/GetChargebackKindCalculations',
      InsertChargebackKind: '/cst/InsertChargebackKind',
      UpdateChargebackKind: '/cst/UpdateChargebackKind',
      DeleteChargebackKind: '/cst/DeleteChargebackKind?',
    },
    FunctionDefinition: {
      GetFunctionDefinition: '/cst/GetFunctionDefinition?',
      GetFunctionsScope: '/cst/GetFunctionsScope',
      GetFunctionsOutput: '/cst/GetFunctionsOutput',
      InsertFunctionDefinition: '/cst/InsertFunctionDefinition',
      UpdateFunctionDefinition: '/cst/UpdateFunctionDefinition',
      DeleteFunctionDefinition: '/cst/DeleteFunctionDefinition?',
    },
    Regions: {
      GetRegions: '/cst/GetRegions',
      InsertRegion: '/cst/InsertRegion',
      UpdateRegion: '/cst/UpdateRegion',
      DeleteRegion: '/cst/DeleteRegion?',
    },
    ComplainSubjects: {
      GetComplainDefinitonAgainst: '/cst/GetComplainDefinitonAgainst',
      InsertComplainDefinitonAgainst: '/cst/InsertComplainDefinitonAgainst?',
      UpdateComplainDefinitonAgainst: '/cst/UpdateComplainDefinitonAgainst?',
      DeleteComplainDefinitonAgainst: '/cst/DeleteComplainDefinitonAgainst?',
      GetComplainDefinitonCategory: '/cst/GetComplainDefinitonCategory?',
      InsertComplainDefinitonCategory: '/cst/InsertComplainDefinitonCategory?',
      UpdateComplainDefinitonCategory: '/cst/UpdateComplainDefinitonCategory?',
      DeleteComplainDefinitonCategory: '/cst/DeleteComplainDefinitonCategory?',
      GetComplainDefinitonSubCategory: '/cst/GetComplainDefinitonSubCategory?',
      GetSubCategoryYesNo: '/cst/GetSubCategoryYesNo',
      GetSubCategoryType: '/cst/GetSubCategoryType',
      InsertComplainDefinitonSubCategory:
        '/cst/InsertComplainDefinitonSubCategory?',
      UpdateComplainDefinitonSubCategory:
        '/cst/UpdateComplainDefinitonSubCategory?',
      DeleteComplainDefinitonSubCategory:
        '/cst/DeleteComplainDefinitonSubCategory?',
      GetComplainDefinitonChargeback: '/cst/GetComplainDefinitonChargeback?',
      GetChargebackKinds: '/cst/GetChargebackKinds',
      InsertComplainDefinitonChargeback:
        '/cst/InsertComplainDefinitonChargeback?',
      UpdateComplainDefinitonChargeback:
        '/cst/UpdateComplainDefinitonChargeback?',
      DeleteComplainDefinitonChargeback:
        '/cst/DeleteComplainDefinitonChargeback?',
    },
  };

  static readonly ColDef = {
    "monitoring": [
        {
          "colId": "Installer",
          "hide": false,
          "aggFunc": null,
          "width": 220,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "InstallerType",
          "hide": false,
          "aggFunc": null,
          "width": 100,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Duration",
          "hide": false,
          "aggFunc": null,
          "width": 120,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "params",
          "hide": false,
          "aggFunc": null,
          "width": 60,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "TaskName",
          "hide": false,
          "aggFunc": null,
          "width": 140,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Hours",
          "hide": false,
          "aggFunc": null,
          "width": 70,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "OrderKind",
          "hide": false,
          "aggFunc": null,
          "width": 70,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "TabletId",
          "hide": false,
          "aggFunc": null,
          "width": 60,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "OrderNo",
          "hide": false,
          "aggFunc": null,
          "width": 60,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Method",
          "hide": false,
          "aggFunc": null,
          "width": 65,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Customer",
          "hide": false,
          "aggFunc": null,
          "width": 110,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Days",
          "hide": false,
          "aggFunc": null,
          "width": 30,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "OrderStatus",
          "hide": false,
          "aggFunc": null,
          "width": 65,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "ScheduleStatus",
          "hide": false,
          "aggFunc": null,
          "width": 87,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Sub",
          "hide": false,
          "aggFunc": null,
          "width": 80,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Time",
          "hide": false,
          "aggFunc": null,
          "width": 38,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "LateStart",
          "hide": false,
          "aggFunc": null,
          "width": 70,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "StoreCode",
          "hide": false,
          "aggFunc": null,
          "width": 45,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "City",
          "hide": false,
          "aggFunc": null,
          "width": 70,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "I",
          "hide": false,
          "aggFunc": null,
          "width": 30,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "S",
          "hide": false,
          "aggFunc": null,
          "width": 30,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "F",
          "hide": false,
          "aggFunc": null,
          "width": 30,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "RC",
          "hide": false,
          "aggFunc": null,
          "width": 30,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "RH",
          "hide": false,
          "aggFunc": null,
          "width": 30,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "CW",
          "hide": false,
          "aggFunc": null,
          "width": 30,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Size",
          "hide": false,
          "aggFunc": null,
          "width": 30,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Vacent",
          "hide": false,
          "aggFunc": null,
          "width": 35,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "Distance",
          "hide": false,
          "aggFunc": null,
          "width": 70,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        },
        {
          "colId": "calcDatetime",
          "hide": false,
          "aggFunc": null,
          "width": 70,
          "pivotIndex": null,
          "pinned": null,
          "rowGroupIndex": null
        }
      ]
  }
}
